#!/bin/bash

# Create an output file for the LaTeX table content
output_file="counts_data.tex"
echo "% LaTeX table content generated by extract_counts.sh" > "$output_file"

# Write the LaTeX table header
echo "\\begin{tabular}{|l|$(printf 'r|' $(ls *.counts | wc -l))}" >> "$output_file"
echo "\\hline" >> "$output_file"
echo -n "Metric " >> "$output_file"

# Add column headers for each file
for file in *.counts; do
    echo -n "& ${file%.counts} " >> "$output_file"
done
echo "\\\\ \\hline" >> "$output_file"

# Extract data from each file and fill in the table
metrics=("Unique K-mers" "Distinct K-mers" "Total K-mers" "Maximum Count")

for metric in "${metrics[@]}"; do
    echo -n "$metric " >> "$output_file"
    for file in *.counts; do
        # Extract relevant numbers from the file (adjust grep/sed based on file format)
        value=$(jellyfish dump "$file" | wc -l)  # Example: Get count of k-mers
        echo -n "& $value " >> "$output_file"
    done
    echo "\\\\ \\hline" >> "$output_file"
done

# Close the table
echo "\\end{tabular}" >> "$output_file"

